language: node_js
os: osx
node_js:
  - "stable"
cache:
  yarn: true
  directories:
  - node_modules
script:
  - yarn test
  - yarn run build
deploy:
  provider: s3
  access_key_id: $REACT_APP_AWS_ACCESS_KEY_ID
  secret_access_key: $REACT_APP_AWS_SECRET_ACCESS_KEY
  bucket: $REACT_APP_AWS_BUCKET_NAME
  endpoint: $REACT_APP_AWS_BUCKET_ENDPOINT
  skip_cleanup: true
  local_dir: build
  region: $REACT_APP_AWS_BUCKET_REGION
  on:
    branch: master
